### ISSUE TITLE
Run CircleCI on Pull Requests

### ISSUE THREAD

**Issue by davidag** [Kartones/flask-calendar#13]
I might be missing something, but it looks like CircleCI is not running on PRs. Could it be activated so that tests are run before merging?

**Comment by Kartones** [comment]
It was working only with my branches & PRs as they were from the same user+repo, I've activated on the CircleCI webhook sending it also notifications of any pull request and "pull request comment" so whenever you can, try and let me know if how they're triggered.

Thanks for noticing out!

**Comment by Kartones** [comment]
They aren't run on external forks because of security reasons: https://discuss.circleci.com/t/pull-requests-not-triggering-build/1213/4

So basically you should manually run make test before submitting the PR, which makes sense regarding that it is not the source repo where the CI would run into (it does run upon merging, though).
