### ISSUE TITLE
Is there any documentation?

### ISSUE THREAD

**Issue by lennertcl** [Kartones/flask-calendar#39]
I would like to find the documentation about how to use/integrate the calendar, but it doesn't seem like there is any.

**Comment by Kartones** [comment]
Hi @lennertcl,

I've improved a bit the README, with a new [Setup](https://github.com/Kartones/flask-calendar#setup) section detailing the required steps to use it from nginx + uwsgi.

Hope it helps and is more clear now!

**Comment by lennertcl** [comment]
Thank you for the update!
However I am looking for a way to integrate a calendar into an existing flask app. 

Is there any way to do something like `from flask-calendar import calendar` and integrate it this way so that you can add calendars to the project easily, or are you supposed to merge this repository into the existing project and create calendars this way?

If it is not yet possible to make imports easily, I would be willing to contribute to the project by making it possible to import the calendar and write some documentation for it.

**Comment by Kartones** [comment]
Ahh, ok.

Then the answer is "not directly". You will for sure have to merge the code into any other existing Flask project, because it is coupled to Flask itself. If you take a look at [actions.py](https://github.com/Kartones/flask-calendar/blob/master/flask_calendar/actions.py) they don't have *much* logic, but they have *some* logic other than mere mapping to the business layer/logic.

But I think that doing at your destination Flask app the same imports that [app.py](https://github.com/Kartones/flask-calendar/blob/master/flask_calendar/app.py) does and a few adaptations like the configuration would get you pretty much near the end.

But it is not a direct nor simple path, so of course I'd more than welcome contributions :smiley: please do if you feel it's worth, as long as it keeps working by itself, it'd be great if was modularized more so becomes almost plug and play.

Thank you!

**Comment by lennertcl** [comment]
I will fork and experiment to see what works. Surely I'm not the first person wanting to integrate a calendar in a Flask application. 

Thanks for the help!
